apiVersion: v1
kind: Service
metadata:
  name: hello-world-spring-boot
spec:
  ports:
    - protocol: TCP
      port: 8080      
      targetPort: 8080 
  type: NodePort        
  selector:
    app: hello-world-spring-boot
